In [1]:
import numpy as np
data=np.random.randint(0,100,(5,5))
data

array([[59, 97, 91, 94, 49],
       [93, 66, 14, 68,  8],
       [27, 48, 14, 30, 16],
       [60, 50, 82, 19,  1],
       [52, 71, 89, 68, 40]])

In [2]:
import numpy as np
data=np.random.randint(100,200,(10,10))
data

array([[182, 125, 105, 147, 178, 162, 149, 127, 111, 198],
       [171, 164, 170, 118, 187, 126, 154, 155, 186, 102],
       [100, 109, 133, 167, 188, 175, 163, 109, 184, 122],
       [197, 188, 125, 185, 178, 102, 126, 153, 127, 185],
       [159, 105, 174, 103, 112, 168, 160, 152, 113, 162],
       [184, 156, 115, 100, 147, 192, 160, 136, 112, 159],
       [121, 118, 109, 198, 177, 177, 160, 183, 133, 154],
       [161, 188, 187, 153, 133, 171, 113, 129, 184, 194],
       [195, 165, 136, 140, 162, 162, 139, 159, 160, 139],
       [127, 125, 172, 109, 152, 154, 101, 189, 141, 100]])

In [3]:
type(np.array([1,2,3]))


numpy.ndarray

In [4]:
data[0,0]

np.int64(182)

In [5]:
print(data)
print(" ")

[[182 125 105 147 178 162 149 127 111 198]
 [171 164 170 118 187 126 154 155 186 102]
 [100 109 133 167 188 175 163 109 184 122]
 [197 188 125 185 178 102 126 153 127 185]
 [159 105 174 103 112 168 160 152 113 162]
 [184 156 115 100 147 192 160 136 112 159]
 [121 118 109 198 177 177 160 183 133 154]
 [161 188 187 153 133 171 113 129 184 194]
 [195 165 136 140 162 162 139 159 160 139]
 [127 125 172 109 152 154 101 189 141 100]]
 


In [6]:
data


array([[182, 125, 105, 147, 178, 162, 149, 127, 111, 198],
       [171, 164, 170, 118, 187, 126, 154, 155, 186, 102],
       [100, 109, 133, 167, 188, 175, 163, 109, 184, 122],
       [197, 188, 125, 185, 178, 102, 126, 153, 127, 185],
       [159, 105, 174, 103, 112, 168, 160, 152, 113, 162],
       [184, 156, 115, 100, 147, 192, 160, 136, 112, 159],
       [121, 118, 109, 198, 177, 177, 160, 183, 133, 154],
       [161, 188, 187, 153, 133, 171, 113, 129, 184, 194],
       [195, 165, 136, 140, 162, 162, 139, 159, 160, 139],
       [127, 125, 172, 109, 152, 154, 101, 189, 141, 100]])

In [7]:
data[-2:-1,-2:-1]

array([[160]])

In [8]:
x=[1,2,3]
print(type(x))
y=np.array([1,2,3])
print(type(y))

<class 'list'>
<class 'numpy.ndarray'>


In [9]:
data=np.array([1,2,3,4])
(data-data.min())/(data.max()-data.min())

array([0.        , 0.33333333, 0.66666667, 1.        ])